name: Publish NPM

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    name: Publish to npm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: '' # Desabilita cache
      - name: Clear cache and config
        run: |
          yarn cache clean
          rm -rf ~/.npmrc
          rm -rf .npmrc
          rm -rf node_modules
          rm -rf yarn.lock
      - name: Install
        run: yarn install --no-cache && yarn build
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 